name = "PolyaGammaHybridSamplers"
uuid = "c636ee4f-4591-4d8c-9fae-2dea21daa433"
authors = ["W.Z. Horton"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
